services:
  mysql:
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: btg
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./sql/init_db.sql:/docker-entrypoint-initdb.d/init_db.sql

  rabbitmq:
    image: rabbitmq:3-management
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    ports:
      - "5672:5672"
      - "15672:15672"

  app:
    build: .
    environment:
      DB_HOST: mysql
      DB_NAME: btg
      DB_USER: root
      DB_PASS: example
    depends_on:
      - mysql
      - rabbitmq
    ports:
      - "8080:8080"

volumes:
  mysql_data: